//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod zosta³ wygenerowany przez narzêdzie.
//     Wersja œrodowiska uruchomieniowego: 4.0.30319.42000
//
//     Modyfikacje tego pliku mog¹ spowodowaæ niew³aœciwe zachowanie i zostan¹ utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCarCollectionManager.Properties
{


    /// <summary>
    ///   Silnie typizowana klasa zasobów do wyszukiwania zlokalizowanych ci¹gów itd.
    /// </summary>
    // Ta klasa zosta³a automatycznie wygenerowana za pomoc¹ klasy StronglyTypedResourceBuilder
    // przez narzêdzie, takie jak ResGen lub Visual Studio.
    // Aby dodaæ lub usun¹æ sk³adowe, edytuj plik ResX, a nastêpnie ponownie uruchom narzêdzie ResGen
    // z opcj¹ /str lub ponownie skompiluj projekt programu VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Zwraca buforowane wyst¹pienie sk³adnika ResourceManager u¿ywane przez tê klasê.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfCarCollectionManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Przes³ania w³aœciwoœæ CurrentUICulture bie¿¹cego w¹tku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomoc¹ tej silnie typizowanej klasy zasobów.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
